FROM golang:latest

ARG A_GRPC_HOST=0.0.0.0
ARG A_GRPC_PORT=1111
ARG A_HTTP_PORT=8080

ENV APP_NAME proxy

ENV GRPC_HOST=${A_GRPC_HOST}
ENV GRPC_PORT=${A_GRPC_PORT}
ENV HTTP_PORT=${A_HTTP_PORT}

#RUN go version

RUN mkdir -p ${GOPATH}/src/${APP_NAME}
WORKDIR ${GOPATH}/src/${APP_NAME}

COPY go.mod ./
COPY go.sum ./

COPY ./cmd ./
COPY ./cmd/gateway/ ./cmd/
COPY ./cmd/gateway/* ./cmd/gateway/

COPY ./api ./
COPY ./api/proto ./api/
COPY ./api/proto/* ./api/proto/

#COPY ./third_party ./

COPY ./internal/ ./
COPY ./internal/api ./internal/
COPY ./internal/api/gateway ./internal/api/
COPY ./internal/api/gateway/* ./internal/api/gateway/
COPY ./internal/logger ./internal/
COPY ./internal/logger/* ./internal/logger/

#RUN ls -l
#RUN pwd

RUN go mod download
#RUN protoc -I. -I$GOPATH/src --grpc-gateway_out=logtostderr=true:. api/proto/books.proto
RUN go build cmd/gateway/main.go
RUN ls -l

EXPOSE ${HTTP_PORT}
EXPOSE ${GRPC_PORT}


CMD ./main -grpchost=${GRPC_HOST} -grpcport=${GRPC_PORT} -httpport=${HTTP_PORT}

