// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/books.proto

package books

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Result struct {
	Rez                  string   `protobuf:"bytes,1,opt,name=rez,proto3" json:"rez,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cdbf6debe85f9b4, []int{0}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetRez() string {
	if m != nil {
		return m.Rez
	}
	return ""
}

type OneBook struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OneBook) Reset()         { *m = OneBook{} }
func (m *OneBook) String() string { return proto.CompactTextString(m) }
func (*OneBook) ProtoMessage()    {}
func (*OneBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cdbf6debe85f9b4, []int{1}
}

func (m *OneBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneBook.Unmarshal(m, b)
}
func (m *OneBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneBook.Marshal(b, m, deterministic)
}
func (m *OneBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneBook.Merge(m, src)
}
func (m *OneBook) XXX_Size() int {
	return xxx_messageInfo_OneBook.Size(m)
}
func (m *OneBook) XXX_DiscardUnknown() {
	xxx_messageInfo_OneBook.DiscardUnknown(m)
}

var xxx_messageInfo_OneBook proto.InternalMessageInfo

func (m *OneBook) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OneBook) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *OneBook) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Books struct {
	Books                []*OneBook `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Books) Reset()         { *m = Books{} }
func (m *Books) String() string { return proto.CompactTextString(m) }
func (*Books) ProtoMessage()    {}
func (*Books) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cdbf6debe85f9b4, []int{2}
}

func (m *Books) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Books.Unmarshal(m, b)
}
func (m *Books) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Books.Marshal(b, m, deterministic)
}
func (m *Books) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Books.Merge(m, src)
}
func (m *Books) XXX_Size() int {
	return xxx_messageInfo_Books.Size(m)
}
func (m *Books) XXX_DiscardUnknown() {
	xxx_messageInfo_Books.DiscardUnknown(m)
}

var xxx_messageInfo_Books proto.InternalMessageInfo

func (m *Books) GetBooks() []*OneBook {
	if m != nil {
		return m.Books
	}
	return nil
}

type BookData struct {
	Author               string   `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookData) Reset()         { *m = BookData{} }
func (m *BookData) String() string { return proto.CompactTextString(m) }
func (*BookData) ProtoMessage()    {}
func (*BookData) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cdbf6debe85f9b4, []int{3}
}

func (m *BookData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookData.Unmarshal(m, b)
}
func (m *BookData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookData.Marshal(b, m, deterministic)
}
func (m *BookData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookData.Merge(m, src)
}
func (m *BookData) XXX_Size() int {
	return xxx_messageInfo_BookData.Size(m)
}
func (m *BookData) XXX_DiscardUnknown() {
	xxx_messageInfo_BookData.DiscardUnknown(m)
}

var xxx_messageInfo_BookData proto.InternalMessageInfo

func (m *BookData) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *BookData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type UpdateBookRequest struct {
	BookId               string    `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Msg                  *BookData `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateBookRequest) Reset()         { *m = UpdateBookRequest{} }
func (m *UpdateBookRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBookRequest) ProtoMessage()    {}
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cdbf6debe85f9b4, []int{4}
}

func (m *UpdateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBookRequest.Unmarshal(m, b)
}
func (m *UpdateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBookRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBookRequest.Merge(m, src)
}
func (m *UpdateBookRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBookRequest.Size(m)
}
func (m *UpdateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBookRequest proto.InternalMessageInfo

func (m *UpdateBookRequest) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

func (m *UpdateBookRequest) GetMsg() *BookData {
	if m != nil {
		return m.Msg
	}
	return nil
}

type DeleteBookRequest struct {
	BookId               string   `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookRequest) Reset()         { *m = DeleteBookRequest{} }
func (m *DeleteBookRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBookRequest) ProtoMessage()    {}
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cdbf6debe85f9b4, []int{5}
}

func (m *DeleteBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookRequest.Unmarshal(m, b)
}
func (m *DeleteBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookRequest.Merge(m, src)
}
func (m *DeleteBookRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBookRequest.Size(m)
}
func (m *DeleteBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookRequest proto.InternalMessageInfo

func (m *DeleteBookRequest) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

type PostBookRequest struct {
	Msg                  *BookData `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PostBookRequest) Reset()         { *m = PostBookRequest{} }
func (m *PostBookRequest) String() string { return proto.CompactTextString(m) }
func (*PostBookRequest) ProtoMessage()    {}
func (*PostBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cdbf6debe85f9b4, []int{6}
}

func (m *PostBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostBookRequest.Unmarshal(m, b)
}
func (m *PostBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostBookRequest.Marshal(b, m, deterministic)
}
func (m *PostBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostBookRequest.Merge(m, src)
}
func (m *PostBookRequest) XXX_Size() int {
	return xxx_messageInfo_PostBookRequest.Size(m)
}
func (m *PostBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostBookRequest proto.InternalMessageInfo

func (m *PostBookRequest) GetMsg() *BookData {
	if m != nil {
		return m.Msg
	}
	return nil
}

type GetBookRequest struct {
	BookId               string   `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cdbf6debe85f9b4, []int{7}
}

func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (m *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(m, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

type GetBooksRequest struct {
	Buff                 string   `protobuf:"bytes,1,opt,name=buff,proto3" json:"buff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBooksRequest) Reset()         { *m = GetBooksRequest{} }
func (m *GetBooksRequest) String() string { return proto.CompactTextString(m) }
func (*GetBooksRequest) ProtoMessage()    {}
func (*GetBooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cdbf6debe85f9b4, []int{8}
}

func (m *GetBooksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBooksRequest.Unmarshal(m, b)
}
func (m *GetBooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBooksRequest.Marshal(b, m, deterministic)
}
func (m *GetBooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBooksRequest.Merge(m, src)
}
func (m *GetBooksRequest) XXX_Size() int {
	return xxx_messageInfo_GetBooksRequest.Size(m)
}
func (m *GetBooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBooksRequest proto.InternalMessageInfo

func (m *GetBooksRequest) GetBuff() string {
	if m != nil {
		return m.Buff
	}
	return ""
}

func init() {
	proto.RegisterType((*Result)(nil), "books.Result")
	proto.RegisterType((*OneBook)(nil), "books.OneBook")
	proto.RegisterType((*Books)(nil), "books.Books")
	proto.RegisterType((*BookData)(nil), "books.BookData")
	proto.RegisterType((*UpdateBookRequest)(nil), "books.UpdateBookRequest")
	proto.RegisterType((*DeleteBookRequest)(nil), "books.DeleteBookRequest")
	proto.RegisterType((*PostBookRequest)(nil), "books.PostBookRequest")
	proto.RegisterType((*GetBookRequest)(nil), "books.GetBookRequest")
	proto.RegisterType((*GetBooksRequest)(nil), "books.GetBooksRequest")
}

func init() { proto.RegisterFile("api/proto/books.proto", fileDescriptor_7cdbf6debe85f9b4) }

var fileDescriptor_7cdbf6debe85f9b4 = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x65, 0x9b, 0x38, 0xc9, 0x94, 0x26, 0xed, 0x40, 0x5b, 0xcb, 0x12, 0x52, 0x59, 0x81,
	0x54, 0xbe, 0x6a, 0x29, 0x70, 0x40, 0x9c, 0x10, 0xaa, 0x14, 0x81, 0x90, 0x52, 0x59, 0xf4, 0x1c,
	0x6d, 0xea, 0x6d, 0x63, 0x35, 0x64, 0xcd, 0xee, 0xe4, 0x50, 0x10, 0x17, 0x5e, 0x81, 0x47, 0xe3,
	0xce, 0x89, 0x07, 0x41, 0xfb, 0xe1, 0x36, 0xc4, 0x80, 0xa2, 0xde, 0x66, 0x3c, 0x33, 0xbf, 0xff,
	0x8c, 0x67, 0x16, 0x76, 0x78, 0x55, 0x66, 0x95, 0x92, 0x24, 0xb3, 0x89, 0x94, 0x17, 0xfa, 0xd0,
	0xda, 0xd8, 0xb2, 0x4e, 0xfa, 0x84, 0x84, 0xa6, 0xf1, 0xb9, 0xaa, 0x4e, 0x33, 0x9a, 0x96, 0xaa,
	0x18, 0x57, 0x5c, 0xd1, 0x65, 0x66, 0x6a, 0xf8, 0x7c, 0x2e, 0x89, 0x53, 0x29, 0xe7, 0xbe, 0x86,
	0xa5, 0x10, 0xe7, 0x42, 0x2f, 0x66, 0x84, 0x5b, 0x10, 0x29, 0xf1, 0x39, 0x09, 0xf6, 0x83, 0x83,
	0x6e, 0x6e, 0x4c, 0x36, 0x84, 0xf6, 0x68, 0x2e, 0xde, 0x48, 0x79, 0x81, 0x3d, 0x08, 0xcb, 0xc2,
	0xc6, 0xa2, 0x3c, 0x2c, 0x0b, 0xdc, 0x85, 0x98, 0x2f, 0x68, 0x2a, 0x55, 0x12, 0xda, 0x7c, 0xef,
	0xe1, 0x5d, 0x68, 0x51, 0x49, 0x33, 0x91, 0x44, 0xf6, 0xb3, 0x73, 0xd8, 0x33, 0x68, 0x19, 0x8a,
	0xc6, 0x07, 0xe0, 0x7a, 0x4c, 0x82, 0xfd, 0xe8, 0x60, 0x63, 0xd0, 0x3b, 0x74, 0xed, 0x7b, 0x95,
	0xdc, 0x05, 0xd9, 0x4b, 0xe8, 0x18, 0xf7, 0x88, 0x13, 0x5f, 0x12, 0x0a, 0xfe, 0x2e, 0x14, 0x2e,
	0x0b, 0x8d, 0x60, 0xfb, 0xa4, 0x2a, 0x38, 0x39, 0x9c, 0xf8, 0xb4, 0x10, 0x9a, 0x70, 0x0f, 0xda,
	0x86, 0x3b, 0xf6, 0x03, 0x74, 0xf3, 0xd8, 0xb8, 0x6f, 0x0b, 0xbc, 0x0f, 0xd1, 0x47, 0x7d, 0x6e,
	0x09, 0x1b, 0x83, 0xbe, 0xef, 0xa5, 0x56, 0xce, 0x4d, 0x8c, 0x3d, 0x85, 0xed, 0x23, 0x31, 0x13,
	0xeb, 0x01, 0xd9, 0x0b, 0xe8, 0x1f, 0x4b, 0x4d, 0xcb, 0xb9, 0x5e, 0x23, 0xf8, 0x8f, 0xc6, 0x23,
	0xe8, 0x0d, 0x05, 0xad, 0x25, 0xf0, 0x10, 0xfa, 0x3e, 0x55, 0xd7, 0xb9, 0x08, 0xb7, 0x26, 0x8b,
	0xb3, 0x33, 0x9f, 0x68, 0xed, 0xc1, 0xcf, 0x08, 0xda, 0xef, 0xcb, 0x89, 0xe2, 0xea, 0x12, 0x5f,
	0x43, 0xa7, 0x2e, 0xc1, 0x5d, 0xaf, 0xbf, 0xc2, 0x48, 0x6f, 0x2f, 0xf5, 0xa5, 0x59, 0xef, 0xdb,
	0x8f, 0x5f, 0xdf, 0xc3, 0x0e, 0xc6, 0xee, 0xb8, 0xf0, 0x1d, 0xb4, 0x7d, 0x01, 0xee, 0xfc, 0x09,
	0xa8, 0xeb, 0x57, 0xf6, 0xc8, 0x12, 0x4b, 0x40, 0xdc, 0x72, 0x84, 0xec, 0x8b, 0x9f, 0xe6, 0x2b,
	0x9e, 0x00, 0x5c, 0x2f, 0x08, 0x13, 0x5f, 0xd7, 0xd8, 0x59, 0x83, 0x78, 0xcf, 0x12, 0xf7, 0xd2,
	0x06, 0xf1, 0x95, 0xf9, 0x85, 0xf8, 0x01, 0xba, 0xc7, 0x9c, 0x4e, 0xa7, 0x37, 0xa3, 0x0e, 0xfe,
	0x41, 0x1d, 0x01, 0x5c, 0x2f, 0xff, 0x0a, 0xdb, 0xb8, 0x87, 0x74, 0xd3, 0x47, 0xdc, 0x43, 0xaa,
	0xa7, 0x7f, 0xdc, 0x9c, 0x7e, 0x08, 0x9d, 0xfa, 0x3e, 0xae, 0x76, 0xb1, 0x72, 0x30, 0x8d, 0x1e,
	0xef, 0x58, 0xda, 0x26, 0xf3, 0xdb, 0xb0, 0x9d, 0x4d, 0x62, 0xfb, 0x78, 0x9f, 0xff, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x28, 0x31, 0x2c, 0x28, 0x09, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LibraryClient is the client API for Library service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LibraryClient interface {
	GetBooks(ctx context.Context, in *GetBooksRequest, opts ...grpc.CallOption) (*Books, error)
	GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*OneBook, error)
	UpdateBook(ctx context.Context, in *UpdateBookRequest, opts ...grpc.CallOption) (*OneBook, error)
	PatchBook(ctx context.Context, in *UpdateBookRequest, opts ...grpc.CallOption) (*OneBook, error)
	DeleteBook(ctx context.Context, in *DeleteBookRequest, opts ...grpc.CallOption) (*Result, error)
	PostBook(ctx context.Context, in *PostBookRequest, opts ...grpc.CallOption) (*OneBook, error)
}

type libraryClient struct {
	cc *grpc.ClientConn
}

func NewLibraryClient(cc *grpc.ClientConn) LibraryClient {
	return &libraryClient{cc}
}

func (c *libraryClient) GetBooks(ctx context.Context, in *GetBooksRequest, opts ...grpc.CallOption) (*Books, error) {
	out := new(Books)
	err := c.cc.Invoke(ctx, "/books.Library/GetBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*OneBook, error) {
	out := new(OneBook)
	err := c.cc.Invoke(ctx, "/books.Library/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) UpdateBook(ctx context.Context, in *UpdateBookRequest, opts ...grpc.CallOption) (*OneBook, error) {
	out := new(OneBook)
	err := c.cc.Invoke(ctx, "/books.Library/UpdateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) PatchBook(ctx context.Context, in *UpdateBookRequest, opts ...grpc.CallOption) (*OneBook, error) {
	out := new(OneBook)
	err := c.cc.Invoke(ctx, "/books.Library/PatchBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) DeleteBook(ctx context.Context, in *DeleteBookRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/books.Library/DeleteBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryClient) PostBook(ctx context.Context, in *PostBookRequest, opts ...grpc.CallOption) (*OneBook, error) {
	out := new(OneBook)
	err := c.cc.Invoke(ctx, "/books.Library/PostBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LibraryServer is the server API for Library service.
type LibraryServer interface {
	GetBooks(context.Context, *GetBooksRequest) (*Books, error)
	GetBook(context.Context, *GetBookRequest) (*OneBook, error)
	UpdateBook(context.Context, *UpdateBookRequest) (*OneBook, error)
	PatchBook(context.Context, *UpdateBookRequest) (*OneBook, error)
	DeleteBook(context.Context, *DeleteBookRequest) (*Result, error)
	PostBook(context.Context, *PostBookRequest) (*OneBook, error)
}

// UnimplementedLibraryServer can be embedded to have forward compatible implementations.
type UnimplementedLibraryServer struct {
}

func (*UnimplementedLibraryServer) GetBooks(ctx context.Context, req *GetBooksRequest) (*Books, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBooks not implemented")
}
func (*UnimplementedLibraryServer) GetBook(ctx context.Context, req *GetBookRequest) (*OneBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (*UnimplementedLibraryServer) UpdateBook(ctx context.Context, req *UpdateBookRequest) (*OneBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBook not implemented")
}
func (*UnimplementedLibraryServer) PatchBook(ctx context.Context, req *UpdateBookRequest) (*OneBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchBook not implemented")
}
func (*UnimplementedLibraryServer) DeleteBook(ctx context.Context, req *DeleteBookRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBook not implemented")
}
func (*UnimplementedLibraryServer) PostBook(ctx context.Context, req *PostBookRequest) (*OneBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostBook not implemented")
}

func RegisterLibraryServer(s *grpc.Server, srv LibraryServer) {
	s.RegisterService(&_Library_serviceDesc, srv)
}

func _Library_GetBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).GetBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/books.Library/GetBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).GetBooks(ctx, req.(*GetBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/books.Library/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/books.Library/UpdateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).UpdateBook(ctx, req.(*UpdateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_PatchBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).PatchBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/books.Library/PatchBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).PatchBook(ctx, req.(*UpdateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/books.Library/DeleteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).DeleteBook(ctx, req.(*DeleteBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Library_PostBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServer).PostBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/books.Library/PostBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServer).PostBook(ctx, req.(*PostBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Library_serviceDesc = grpc.ServiceDesc{
	ServiceName: "books.Library",
	HandlerType: (*LibraryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBooks",
			Handler:    _Library_GetBooks_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _Library_GetBook_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _Library_UpdateBook_Handler,
		},
		{
			MethodName: "PatchBook",
			Handler:    _Library_PatchBook_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _Library_DeleteBook_Handler,
		},
		{
			MethodName: "PostBook",
			Handler:    _Library_PostBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/books.proto",
}
